version: '3.3'

services:
  web:
    build: .
    image: asset_management_web:latest 
    container_name: asset_management_container
    command: 
      - bash
      - -c
      - |
       python manage.py makemigrations
       python manage.py migrate
       python manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/asset_management
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - 'db'
    
  db:
    image: mysql
    container_name: asset_management_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro

