# Generated by Django 4.2.4 on 2023-09-02 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='conditionlog',
            options={'ordering': ['-allocation_date'], 'verbose_name': 'Condition Log'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_employee', 'Can view employee'), ('can_view_manager', 'Can view manager'), ('can_allocate_asset', 'Can allocate asset'), ('can_deallocate_asset', 'Can deallocate asset'), ('can_view_asset', 'Can view asset'), ('can_add_asset', 'Can add asset'), ('can_edit_asset', 'Can edit asset'), ('can_delete_asset', 'Can delete asset'), ('can_view_asset_condition', 'Can view asset condition'), ('can_add_asset_condition', 'Can add asset condition'), ('can_edit_asset_condition', 'Can edit asset condition'), ('can_delete_asset_condition', 'Can delete asset condition'), ('can_return_asset', 'Can return asset')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_employees', to='assets.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
